ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS class TEXT NOT NULL DEFAULT 'Unknown';
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "busId" TEXT;
ALTER TABLE "AttendanceEvent" ADD COLUMN IF NOT EXISTS resolved BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AttendanceEvent" ADD COLUMN IF NOT EXISTS "resolutionNote" TEXT;
