listener 8883
protocol mqtt

tls_version tlsv1.2
cafile /etc/letsencrypt/live/yourdomain.example.com/chain.pem
certfile /etc/letsencrypt/live/yourdomain.example.com/fullchain.pem
keyfile /etc/letsencrypt/live/yourdomain.example.com/privkey.pem
require_certificate false

allow_anonymous false
password_file /mosquitto/certs/passwd

persistence true
persistence_location /mosquitto/data/

max_connections 1000
